### ISSUE TITLE
getting error while building project 

### ISSUE THREAD

**Issue by ankurb0308** [jaiew/play-jooq#7]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\ankur.bhargava>java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

C:\Users\ankur.bhargava>scala
Welcome to Scala version 2.9.1.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.
7.0_60).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :quit

C:\Users\ankur.bhargava>f:

F:>cd F:\pslp16\play-jooq-master\project-code

F:\pslp16\play-jooq-master\project-code>play run
java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lsca
la/collection/immutable/StringOps;
        at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:129)
        at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
        at sbt.StandardMain$.<init>(Main.scala:52)
        at sbt.StandardMain$.<clinit>(Main.scala)
        at sbt.xMain.run(Main.scala:26)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.NoSuchMethodError: scala.Predef$.augmentSt
ring(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
Press any key to continue . . .

**Comment by ankurb0308** [comment]
finally able to publish plugin.., I know it would be pain for you but if you would able to provide some guide (spoon feed) then it would be bible for play + jOOQ bignners. 

Further can you please advice on how do we hook Transaction manager in this along with this can you please suggest how do we handle connection pooling here if we use Play 2.3.0 + jOOQ.

Thanks & Regards,
Ankur
